version: "3"

networks:
  moviezone:

services:
  frontend:
    build: ./mozi-frontend
    ports:
      - "3000:3000"
    networks:
      - moviezone
    
  backend:
    build: ./mozi-backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - moviezone

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    env_file:
      - ./mysql.env
    volumes:
      - moviezonedb:/var/lib/mysql
    networks:
      - moviezone
volumes:
  moviezonedb: