name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push frontend Docker image
      with:
        image: hamzabalazs/moviezone
        tags: frontend-v1.0.0, latest
        registry: docker.io
        dockerfile: mozi-frontend/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push backend Docker image
      with:
        image: hamzabalazs/moviezone
        tags: backend-v1.0.0, latest
        registry: docker.io
        dockerfile: mozi-backend/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
