name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-for-existing-docker-image-frontend:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      result: ${{ steps.image_exists.conclusion }}  
      image: ${{ steps.image_exists.outputs.image }}
      tag: ${{ steps.image_exists.outputs.tag }}
      current-version: ${{ steps.package-version.outputs.current-version }}
    steps:  
      - uses: actions/checkout@v3
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: ./mozi-frontend
      - name: Check image
        id: image_exists
        uses: cloudposse/github-action-docker-image-exists@main
        with:
          registry: registry.hub.docker.com
          organization: "${{ github.event.repository.owner.login }}"
          repository: "${{ github.event.repository.name }}"
          login: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}"
          tag: frontend-v${{steps.package-version.outputs.current-version}}
      - run: echo ${{ steps.image_exists.conclusion }}

  check-for-existing-docker-image-backend:
    runs-on: ubuntu-latest
    continue-on-error: true  
    outputs:
      result: ${{ steps.image_exists.conclusion }}  
      image: ${{ steps.image_exists.outputs.image }}
      tag: ${{ steps.image_exists.outputs.tag }}
      current-version: ${{ steps.package-version.outputs.current-version }}
    steps:  
      - uses: actions/checkout@v3
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: ./mozi-backend
      - name: Check image
        id: image_exists
        uses: cloudposse/github-action-docker-image-exists@main
        with:
          registry: registry.hub.docker.com
          organization: "${{ github.event.repository.owner.login }}"
          repository: "${{ github.event.repository.name }}"
          login: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}"
          tag: backend-v${{steps.package-version.outputs.current-version}}
      - run: echo ${{ steps.image_exists.conclusion }}
      

  build-frontend:

    runs-on: ubuntu-latest
    needs: check-for-existing-docker-image-frontend
    if: needs.check-for-existing-docker-image-frontend.outputs.result == 'failure'
    steps:
    - uses: actions/checkout@v3
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push frontend Docker image
      with:
        image: hamzabalazs/moviezone
        tags: frontend-v${{ needs.check-for-existing-docker-image-frontend.outputs.current-version }}
        registry: docker.io
        directory: ./mozi-frontend
        dockerfile: mozi-frontend/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    
  
  build-backend:

    runs-on: ubuntu-latest
    needs: check-for-existing-docker-image-backend
    if: needs.check-for-existing-docker-image-backend.outputs.result == 'failure'
    steps:
    - run: echo ${{needs.check-for-existing-docker-image-backend.outputs.result}}
    - run: echo ${{needs.check-for-existing-docker-image-backend.outputs.current-version}}
    - uses: actions/checkout@v3
    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push backend Docker image
      with:
        image: hamzabalazs/moviezone
        tags: backend-v${{ needs.check-for-existing-docker-image-backend.outputs.current-version }}
        registry: docker.io
        directory: ./mozi-backend
        dockerfile: mozi-backend/Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
